### PR TITLE
Update Standard Name Rules table for dimensionless units, change variables improperly using "1" to "fraction"

### PR DESCRIPTION
**Pull request by mkavulich**
Related to Issue #26 and discussion therein, this PR updates the Standard Name Rules table for dimensionless units, removing some ambiguity in wording, separating out "frac" from "percent" entries (since fractions and percentages are different things, and can theoretically be converted) and clarifying when "1" should be used. In addition, several standard names that reference fractions are updated to appropriately use "frac" rather than "1".

### CODE REVIEW

**Review by nusbaume — COMMENTED** [review]
Thanks for tackling this @mkavulich!  Would you be willing to add a couple extra unit changes to this PR?  Specifically the following:

1. `cellular_automata_seed_probability` currently has units of `fraction`.  Might be worth changing that to `frac`.
2.   `chemical_tracer_scavenging_fractions`  should probably also have units of `frac`.

Otherwise I think everything else looks good, at least to me.

**Comment by climbfuji** [comment]
Why can we not spell out fraction? We also spell out percent. The 8-character limit in F77 is history!

**Comment by mkavulich** [comment]
@climbfuji I'm just going off the existing conventions; all the schemes in ccpp-physics currently use `frac`. But if we're okay with committing to that change then I'm all for using `fraction`.

**Comment by nusbaume** [comment]
I'm personally fine with either `frac` or `fraction`, just as long as we aren't using both of them together.  I also agree that `fraction` is certainly less ambiguous (but would require more effort on this particular PR).

**Review by gold2718 — APPROVED** [review]
Looks okay for me

**Comment by climbfuji** [comment]
If it's not too much work, can you change all `frac` to `fraction` please?

**Review by cacraigucar — APPROVED** [review]

**Comment by mkavulich** [comment]
@nusbaume @climbfuji I have made the suggested changes

**Review by climbfuji — APPROVED** [review]
Thanks for considering my comments!

**Review by nusbaume — APPROVED** [review]
Looks great to me now, thanks!

**Pull request merged**
