### PR TITLE
Fix CODEOWNERS so that not only ss421 gets notified/must approve

### PR DESCRIPTION
**Pull request by climbfuji**
Update CODEOWNERS. See in the file itself: "Order is important. The last matching pattern has the most precedence."

See right hand side for a demonstration that the current file is wrong.

### CODE REVIEW

**Comment by climbfuji** [comment]
@cacraigucar @climbfuji @dustinswales @gold2718 @grantfirl @mattldawson @mkavulich @mwaxmonsky @nusbaume @peverwhee @svahl991 @MayeulDestouches - tagging you here instead of adding you as reviewers manually so that you can see the problem yourself.

**Review by ss421 — APPROVED** [review]
Thanks. Happy with the change. I think we should remove @MayeulDestouches from the list (or update) because he is no-longer at the UKMO. Perhaps that could be done in a seperate change.

**Comment by climbfuji** [comment]
> Thanks. Happy with the change. I think we should remove @MayeulDestouches from the list (or update) because he is no-longer at the UKMO. Perhaps that could be done in a separate change.

Good point - do you want to nominate another UKMO representative in addition to yourself?

**Comment by ss421** [comment]
> > Thanks. Happy with the change. I think we should remove @MayeulDestouches from the list (or update) because he is no-longer at the UKMO. Perhaps that could be done in a separate change.
> 
> Good point - do you want to nominate another UKMO representative in addition to yourself?

Yes that would be good. Ill see if I can get someone else that could be added. Thankyou.

**Pull request merged**
